language: java

sudo: false

addons:
  hosts:
    - db

services:
  - docker

install:
  # Build database image.
  - docker build -t database db/.
  # Run the database image.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  # Build and install the application.
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - mvn clean
  - mvn dependency::tree
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc

jobs:
  include:
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      script: mvn test -Dtest=Sem.UnitTests
    - stage: integration tests
      jdk: oraclejdk11
      script: mvn test -Dtest=Sem.AppIntegrationTest

stages:
  - unit tests
  - integration tests