language: java
sudo: false
addons:
  hosts:
  - db
services:
- docker
install:
- pwd
- ls
- ls src/db/
- docker build -t database src/db/.
- docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- mvn clean
- mvn dependency::tree
- echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc
jobs:
  include:
  - stage: unit tests
    install: skip
    jdk: oraclejdk11
    script: mvn test -Dtest=Sem.UnitTests
  - stage: integration tests
    jdk: oraclejdk11
    script: mvn test -Dtest=Sem.AppIntegrationTest
stages:
- unit tests
- integration tests
before_install:
- openssl aes-256-cbc -K $encrypted_a1feeff4c407_key -iv $encrypted_a1feeff4c407_iv
  -in client-secret.json.enc -out client-secret.json -d
