@startuml


actor A1 as "Manager" #green
rectangle Database

rectangle "Application" {
usecase UC1 as "Main Menu"
usecase UC2 as "Country Report"
usecase UC3 as "Capital City Report"
usecase UC4 as "Population Report"
usecase UC5 as "City Report"
usecase UC6 as "Language Report"

A1 -> UC1
UC1 ..> UC2 : Extends
UC1 ..> UC3 : Extends
UC1 ..> UC4 : Extends
UC1 ..> UC5 : Extends
UC1 ..> UC6 : Extends

UC2 -- Database
UC3 - Database
UC4 - Database
UC5 - Database
UC6 - Database

}





@enduml